apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-sf
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.21.1-alpine
        ports:
        - containerPort: 80
        volumeMounts:
        - name: auth-basic
          mountPath: "/etc/nginx/conf.d/.htpasswd"
          readOnly: true
        - name: config  
          mountPath: "/etc/nginx"
          readOnly: true
        env:
        - name: NGINX_USERNAME
          valueFrom:
            secretKeyRef:
              name: auth-basic
              key: user1
        - name: NGINX_PASSWORD
          valueFrom:
            secretKeyRef:
              name: auth-basic
              key: password
      volumes:
        - name: config
          configMap:
            name: nginx-config
            items:
            - key: nginx.config
              path: nginx.conf
        - name: auth-basic
          secret:
            secretName: auth-basic
